#!/usr/bin/env bash

main()
{
	local stream

	stream=$(twitch -g | rofi -dmenu | awk '{print $1}')

	if [ -z "${stream}" ]; then
		return
	fi

	exec twitch --mpv "${stream}" > /dev/null
}

main "$@"

